config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:create, :destroy]
  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'events#index'
  resources :users, only: [:show, :edit, :update]
  resources :events do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  is_impressionable counter_cache: true

  with_options presence: true, format: { with: /\A[0-9]+\z/ } do
    validates :charge, numericality: { only_integer: true, greater_than_or_equal_to: 100, less_than_or_equal_to: 30_000 },
                      presence: { message: "Can't be blank" }
  end

  validates :title, :date, :place, :content, :image, presence: true
  has_one_attached :image
  belongs_to :user
  has_many :likes
  has_many :comments

  def self.search(search)
    if search != ""
      Event.where('content LIKE(?)', "%#{search}%")
    else
      Event.all
    end
  end

  
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'J-POP' },
    { id: 3, name: 'ROCK' },
    { id: 4, name: 'PUNK' },
    { id: 5, name: 'METAL' },
    { id: 6, name: 'HIP-HOP' },
    { id: 7, name: 'レゲエ' },
    { id: 8, name: 'TRAP' },
    { id: 9, name: 'DUBSTEP' },
    { id: 10, name: 'CHILL' },
    { id: 11, name: 'DANCE-MUSIC' },
    { id: 12, name: 'K-POP' },
    { id: 13, name: "DRUM'N'BASE" },
    { id: 14, name: 'R&B' },
    { id: 15, name: 'POPS' },
    { id: 16, name: 'HOUSE' }
  ]

  include ActiveHash::Associations
  has_many :users
  end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :genre


  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, message: "is invalid"

  validates :nickname, :image, :profile, presence: true
  validates :artist_name, presence: true
  has_one_attached :image
  has_many :events, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  has_many :likes
  has_many :comments

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  def liked_by?(event_id)
    likes.where(event_id: event_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :artist_name, :profile, :url, :genre_id, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/events/#{comment.event.id}"
  end



  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, event_id: params[:event_id])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_hot_event, only: [:index]

  def index
    @events = Event.all.order("created_at DESC")
    @hot_event = @hot.limit(1).offset(0)
    @hot_event2 = @hot.limit(1).offset(1)
    @hot_event3 = @hot.limit(1).offset(2)
  end


  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    impressionist(@event, nil, unique: [:ip_address])
    @comment = Comment.new
    @comments = @event.comments.includes(:user)
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end

  def search
    @events = Event.search(params[:keyword]).order("created_at DESC")
  end


  private

  def event_params
    params.require(:event).permit(:image, :title, :date, :place, :charge, :content).merge(user_id: current_user.id)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def set_hot_event
    @hot = Event.order(impressions_count: 'DESC')
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :event_params

  def create
    Like.create(user_id: current_user.id, event_id: params[:id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, event_id: params[:id]).destroy
  end


  private

  def event_params
    @event = Event.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    following = current_user.follow(@user)
    following.save
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
    end
  end

  private
  def set_user
    @user = User.find(params[:follow_id])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :destroy]

  def show
    @events = @user.events.order("created_at DESC")
    @user.url = @user.url.last(11)
  end


  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to "/users/#{current_user.id}"
    else
      render :edit
    end
  end

  def destroy

  end

  private

  def user_params
    params.require(:user).permit(:nickname, :artist_name, :email, :image, :profile, :genre_id, :url, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evesic37351</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_comment.html.erb
<% if @comments.present? %>
  <div class="comments">
    <% comments.each do |comment| %>
      <p>
        <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}", class: "eventuser_btn"%></strong>
        <%= comment.text %>
      </p>
    <% end %>
  </div>
<% end %>
<div class='comment-form'>
  <% if user_signed_in? %>
    <%= form_with(model: [@event, @comment], local: true, class: "show-form") do |form| %>
      <%= form.text_area :text, placeholder: "コメントする", class: "comment-text" %>
      <%= form.submit "SEND", class: "comment-submit" %>
    <% end %>
  <% end %>
</div>

app/views/shared/_email.html.erb
<% if user_signed_in? && current_user.id != user.id && current_user.following?(user) && user.following?(current_user) %>
  <div class='email'>Email:<%= user.email%></div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_follow.html.erb
<% if current_user.following?(user) %>
  <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }, remote: true) do |f| %>
    <%= hidden_field_tag :follow_id, user.id %>
    <%= f.submit 'フォロー解除', class: 'unfollow_btn' %>
  <% end %>
<% else %>
  <%= form_for(current_user.relationships.build, remote: true) do |f| %>
    <%= hidden_field_tag :follow_id, user.id %>
    <%= f.submit 'フォロー', class: 'follow_btn' %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">Place sticky footer content here.</span>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Evesic</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#" class="nav-link px-2 text-white">About</a></li>
          <% if user_signed_in? %>
              <li><%= link_to 'Like', "#", class: "nav-link px-2 text-white" %></li>
              <li><%= link_to 'MyPage', "/users/#{current_user.id}", class: "nav-link px-2 text-white" %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link px-2 text-white" %></li>
          <% else %>
              <%= link_to 'Login', new_user_session_path, class: "nav-link px-2 text-white" %>
              <%= link_to 'Sign-up', new_user_registration_path, class: "nav-link px-2 text-white" %>
          <% end %>
        </ul>
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%= form_with(url: search_events_path, local: true, method: :get, class: "d-flex") do |form| %>
          <%= form.text_field :keyword, placeholder: "Search", class: "form-control me-2" %>
          <%= form.submit "Search", class: "btn btn-outline-success" %>
        <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_like.html.erb
<% if current_user.liked_by?(event.id) %>
  <div class='like_space'>
  <div class='like_count'>
    <%= event.likes.count %>
  </div>
    <%= link_to destroy_like_path(event.id), method: :DELETE, remote: true do %>
      <%= image_tag 'unlike.png', size: '22x22' ,class: "like_btn" %>
    <% end %>
  </div>
<% else %>
  <div class='like_space'>
  <div class='like_count'>
    <%= event.likes.count %>
  </div>
    <%= link_to create_like_path(event.id), method: :POST, remote: true do %>
     <%= image_tag 'like.png', size: '22x22' ,class: "like_btn" %>
    <% end %>
  </div>
<% end %>

app/views/shared/_second-footer.html.erb
<footer class='second-fotter'>
  <div class='second-fotter-text-wrap'>
    <p class='second-fotter-text'>プライバシーポリシー</p>
    <p class='second-fotter-text'>EVESIC利用規約</p>
  </div>
</footer>