config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:create, :destroy]
  get 'users/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'events#index'
  resources :users, only: [:show, :edit, :update]
  resources :events do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

end

app/models/event.rb
class Event < ApplicationRecord
  is_impressionable counter_cache: true

  with_options presence: true, format: { with: /\A[0-9]+\z/ } do
    validates :charge, numericality: { only_integer: true, greater_than_or_equal_to: 100, less_than_or_equal_to: 30_000 },
                      presence: { message: "Can't be blank" }
  end

  validates :title, :date, :place, :content, :image, presence: true
  has_one_attached :image
  belongs_to :user
  has_many :likes
  has_many :comments

  def self.search(search)
    if search != ""
      Event.where('content LIKE(?)', "%#{search}%")
    else
      Event.all
    end
  end

  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_hot_event, only: [:index]

  def index
    @events = Event.all.order("created_at DESC")
    @hot_event = @hot.limit(1).offset(0)
    @hot_event2 = @hot.limit(1).offset(1)
    @hot_event3 = @hot.limit(1).offset(2)
  end


  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    impressionist(@event, nil, unique: [:ip_address])
    @comment = Comment.new
    @comments = @event.comments.includes(:user)
  end

  def edit
  end

  def update
    if @event.update(event_params)
      redirect_to event_path
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end

  def search
    @events = Event.search(params[:keyword]).order("created_at DESC")
  end


  private

  def event_params
    params.require(:event).permit(:image, :title, :date, :place, :charge, :content).merge(user_id: current_user.id)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def set_hot_event
    @hot = Event.order(impressions_count: 'DESC')
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<div class="items-sell-contents">
  <header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Evesic</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <div class="d-flex">
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">イベント情報を入力</h2>
    <%= form_with model: @event, local: true do |f| %>


    <%= render 'shared/error_messages', model: f.object %>


    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        イベントフライヤー
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックして画像をアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        イベント名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"イベント名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
    <div class='form-text-wrap'>
      <label class="weight-bold-text">開催日
      <span class="indispensable">必須</span></label>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2022,
                    end_year: (Time.now.year + 3),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <div class="weight-bold-text">
        開催場所
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :place, class:"items-text", id:"item-name", placeholder:"場所（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          イベント概要
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :content, class:"items-text2", id:"item-info", placeholder:"イベントの概要（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>
    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>入場料<br>(¥100〜30,000)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>入場料</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :charge, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#"></a>
        <a href="#"></a>
        
      </p>
      <p class="sentence">
        
        <a href="#"></a>
        
      </p>
      <p class="sentence">
        
        <a href="#"></a>
        
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "編集する" ,class:"sell-btn" %>
      <%=link_to 'もどる', event_path(@event.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>
<%= render "shared/second-footer"%>

app/views/events/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Carousel Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
  </head>
  <body>

<%= render "shared/header" %>

<main>

  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
    <% if @hot_event.present? %>
    <% @hot_event.each do |hot| %>
      <div class="carousel-item active">
        <%= image_tag hot.image, class: "bd-placeholder-img" if hot.image.attached? %> 
        <div class="container">
          <div class="carousel-caption text-start">
            <h1><%= hot.title%></h1>
            <p><%= "#{hot.content.first(100)}..." %></p>
            <%= link_to 'more', event_path(hot.id), class: "btn btn-lg btn-primary" %>
          </div>
        </div>
      </div>
      <% end %>
    <% else %>
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>Example headline.</h1>
            <p>Some representative placeholder content for the first slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
    <% end %>
    <% if @hot_event2.present? %>
      <% @hot_event2.each do |hot2| %>
      <div class="carousel-item">
        <%= image_tag hot2.image, class: "bd-placeholder-img" if hot2.image.attached? %> 
        <div class="container">
          <div class="carousel-caption">
            <p><%= "#{hot2.content.first(100)}..." %></p>
            <h1><%= hot2.title%></h1>
            <%= link_to 'more', event_path(hot2.id), class: "btn btn-lg btn-primary" %>
          </div>
        </div>
      </div>
      <% end %>
      <% else %>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>Another example headline.</h1>
            <p>Some representative placeholder content for the second slide of the carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
    <% end %>
    <% if @hot_event3.present? %>
      <% @hot_event3.each do |hot3| %>
      <div class="carousel-item">
        <%= image_tag hot3.image, class: "bd-placeholder-img" if hot3.image.attached? %> 
        <div class="container">
          <div class="carousel-caption text-end">
            <h1><%= hot3.title%></h1>
            <p><%= "#{hot3.content.first(100)}..." %></p>
            <%= link_to 'more', event_path(hot3.id), class: "btn btn-lg btn-primary" %>
          </div>
        </div>
      </div>
      <% end %>
      <% else %>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>One more for good measure.</h1>
            <p>Some representative placeholder content for the third slide of this carousel.</p>
            <p><a class="btn btn-lg btn-primary" href="#">Browse gallery</a></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @events.each do |event| %>
        <div class="col">
          <div class="card shadow-sm">
            <%= link_to event_path(event.id) do %>
              <%= image_tag event.image.variant(resize: '100%x80%'), class: "bd-placeholder-img card-img-top"  if event.image.attached? %> 
            <% end %>
                <div class="card-body">
                <h6><%= event.title %></h6>
                    <p class="small"><%= "#{event.content.first(54)}..." %></p>
                      <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                      <small class="text-muted">場所<br><%= event.place %></small>
                    </div>
                    <small class="text-muted">開催日<br><%= event.date%></small>
                  </div>
              </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
  <% if user_signed_in? %>
    <%= link_to new_event_path, class: 'purchase-btn' do %>
      <span class='event-btn-text'>Post Event</span>
        <%= image_tag 'icon_speaker.png', size: '250x40' ,class: "purchase-btn-icon" %>
    <% end %>
  <% end %>
  </main>
  <%= render "shared/footer" %>
  </body>
</html>

app/views/events/new.html.erb
<div class="items-sell-contents">
  <header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Evesic</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <div class="d-flex">
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">イベント情報を入力</h2>
    <%= form_with model: @event, local: true do |f| %>


    <%= render 'shared/error_messages', model: f.object %>


    <div class="img-upload">
      <div class="weight-bold-text">
        イベントフライヤー
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックして画像をアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <div class="new-items">
      <div class="weight-bold-text">
        イベント名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"items-text", id:"item-name", placeholder:"イベント名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
    <div class='form-text-wrap'>
      <label class="weight-bold-text">開催日
      <span class="indispensable">必須</span></label>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2022,
                    end_year: (Time.now.year + 3),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <div class="weight-bold-text">
        開催場所
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :place, class:"items-text", id:"item-name", placeholder:"場所（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          イベント概要
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :content, class:"items-text2", id:"item-info", placeholder:"イベントの概要（必須 1,000文字まで）" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>入場料<br>(¥100〜30,000)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>入場料</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :charge, class:"price-input", id:"item-price", placeholder:"例）300" %>
        </div>
      </div>
    </div>
    <div class="caution">
      <p class="sentence">
        <a href="#"></a>
        <a href="#"></a>
        
      </p>
      <p class="sentence">
        
        <a href="#"></a>
        
      </p>
      <p class="sentence">
        
        <a href="#"></a>
        
      </p>
    </div>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
  </div>
  <% end %>
</div>
<%= render "shared/second-footer"%>
<%= render "shared/footer"%>

app/views/events/search.html.erb
<%= render "shared/header" %>
<main>
  <div class='search_box'></div>
  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      <% @events.each do |event| %>
        <div class="col">
          <div class="card shadow-sm">
            <%= link_to event_path(event.id) do %>
              <%= image_tag event.image.variant(resize: '100%x80%'), class: "bd-placeholder-img card-img-top"  if event.image.attached? %> 
            <% end %>
                <div class="card-body">
                <h6><%= event.title %></h6>
                    <p class="small"><%= "#{event.content.first(54)}..." %></p>
                      <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                      <small class="text-muted">場所<br><%= event.place %></small>
                    </div>
                    <small class="text-muted">開催日<br><%= event.date%></small>
                  </div>
              </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
  <%= render "shared/second-footer" %>
</main>

app/views/events/show.html.erb
<%= render "shared/header" %>
<main>
  <div class="container marketing">
    <div class="row featurette">
      <div class="col-md-7">
        <div class='event_title'><h2 class="featurette-heading"><%= @event.title%><br></h2></div>
        <div class='event_place'><h4><span class="text-muted"><%= @event.place%></span></h4></div>
        <div class='event_date'><h5><span class="text-muted"><%=@event.date%></span></h5></div>
        <div class='event_charge'><h5><span class="text-muted"><%="￥#{@event.charge}"%></span></h5></div>
        <p class="lead"><%= @event.content%></p><br>
        <% if user_signed_in? && current_user.id == @event.user.id%>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
            <%= link_to edit_event_path(@event.id), class: "btn btn-sm btn-outline-secondary" do %>
            <%= image_tag 'edit-button.png', size: '25x25'%>
            <% end %>
            <%= link_to event_path, method: :delete, class: "btn btn-sm btn-outline-secondary" do %>
            <%= image_tag 'dust_box.png', size: '25x25' %>
            <% end %>
          </div>
      </div>
    <% elsif user_signed_in? && current_user.id != @event.user.id%>
      <div id='like'>
        <%= render "shared/like", event: @event %>
      </div>
    <% end %>
      </div>
      <div class="col-md-5">
        <div class='space'></div>
        <%= image_tag @event.image, class: "bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto"  if @event.image.attached? %> 
        <h6>投稿者:<%= link_to @event.user.nickname, "/users/#{@event.user.id}", class: "eventuser_btn" %></h6>
      </div>
      
        <div id="comment">
          <%= render "shared/comment", comments: @comments %>
        </div>
    </div>
  </div>
  
</main>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

  </body>

</html>